[project]
name = "retail-data-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "benkivuva", email = "benkivuvak5@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "anthropic>=1.12.1",
    "dbt-bigquery>=1.12.1",
    "dbt-core>=1.12.5",
    "faker>=40.41.0",
    "pandas>=3.0.6",
]

[project.scripts]
retail-data-platform = "retail_data_platform:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
